on:
  push:    
    tags:
      - 'v*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            _**Mudanças nesta Versão**_

            - Primeira Mudança:
              - _Atualizado `OpenCore` para `0.9.6`._
            - Segunda Mudança:
              - _Adicionado em config.plis -> Booter -> Quirk -> `FixupAppleEfiImages`._
            - Terceira Mudança:
              - _Adicionado em EFI -> kexts -> `RestrictEvents.kext`_              
              - _Adicionado em config.plis -> NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args -> `revpatch=sbvmm`:_
          draft: false
          prerelease: false