#Github Actions to create a release and upload a release asset
#Gigabyte Z590 Aorus Pro AX Hackintosh EFI

on:
  push:    
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Uploud EFI to Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Packaging EFIs 
        run: |
          zip -q -r Z590-AORUS-PRO-AX-macOS-Sonoma.zip ./Z590-AORUS-PRO-AX-macOS-Sonoma
          zip -q -r Z590-AORUS-PRO-AX-macOS-Tahoe.zip ./Z590-AORUS-PRO-AX-macOS-Tahoe
          ls -l *.zip

      - name: Generate release tag
        id: tag
        run: |         
            echo "::set-output name=release_tag::$(cat ReleaseTag.txt)"
            cat ReleaseTag.txt
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.tag.outputs.release_tag }}   
          tag_name: ${{ steps.tag.outputs.release_tag }}    
          prerelease: false
          draft: false
          body_path: changelog.md
          files: |
            ./*.zip